let CONSTANTS = {
    TITLE: "ALTIMETRIK",
    HEADER: [{ name: "HOME" }, { name: "PLAYGROUND" }, { name: "CUSTOMER STORIES" }],
    LOGOUT: "Logout",
    DASHBOARD_TITLE: "Dashboards",
    COMPANY_NAME: "Company Name",
    PERFORMANCE: "Performance",
    PERFORMANCE_DETAILS: "High rated in current year",
    REVENUE: "Revenue",
    REVENUE_DETAILS: "US $300 billion",
    WELCOME_MSG_ONE: "Welcome to Altimetrik. We are the catalyst driving digital transformation.",
    WELCOME_MSG_TWO: "You have successfully logged in. You can go through our website by clicking",
    WELCOME_MSG_THREE: " dashboard link",
    LOGIN_ERR_MSG: "Please enter valid username and password.",
    LOGIN_USERNAME_TOOLTIP: "Please enter your valid username",
    LOGIN_PASSWORD_TOOLTIP: "Please enter your valid password",
    LOGIN_BTN_TOOLTIP: "Login into your account",
    CREATE_ACCOUNT_HELP_TEXT: "Don't have an account ? ",
    CREATE_ACCOUNT: "Create Account",
    LOGIN_HELP_TEXT: "Already have an account ? ",
    LOGIN: "Login",
    SIGNUP_SUCCESS: "You have signed up successfully",
    SIGNUP_USERNAME_TOOLTIP: "Please enter username with aplhabets only",
    SIGNUP_PASSWORD_TOOLTIP: "Please enter password with 8 or more character",
    SIGNUP_CONFIRM_PASSWORD_TOOLTIP: "Please re-enter password",
    SIGNUP_EMAIL_TOOLTIP: "Please enter valid email id (Eg: ABC@email.com)",
    SIGNUP_FIRSTNAME_TOOLTIP: "Please enter firstname with aplhabets",
    SIGNUP_LASTNAME_TOOLTIP: "Please enter lastname with aplhabets",
    SIGNUP_GENDER_TOOLTIP: "Please select gender",
    SIGNUP_COUNTRY_TOOLTIP: "Please select any one country from list",
    SIGNUP_BTN_TOOLTIP: "Click signup to create account",
    COUNTRY_LIST: [
        {name: "Australia"}, {name: "Brazil"}, {name: "Canada"}, 
        {name: "Denmark"}, {name: "Egypt"}, {name: "Franch"}, {name: "Germany"}, {name: "Hungary"},
        {name: "India"}, {name: "Spain"}]
}

export { CONSTANTS }